title: Jornadas de analítica deportiva
description: Web de las jornadas de analítica deportiva, 11-12 de septiembre de 2055, UCLM, Ciudad Real
theme: jekyll-theme-minimal
logo: /assets/img/logo_uclm.png
